name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest

    # don't run this on the master branch
    if: github.ref != 'refs/heads/master'

    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2.2.2
      - uses: pre-commit/action@v2.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
